package com.karrot.demo.domain.item;

public enum ItemCategory {
    DIGITAL_DEVICE, HOME_APPLIANCES, FURNITURE, CHILD,
    HOUSEHOLD_PROCESSED_FOOD, CHILD_BOOK, SPORTS, WOMEN_GOODS, WOMEN_CLOTHES,
    MEN_GODDS, GAME_HOBBIES, BEAUTY, PETS, BOOKS_ALBUM, PLANTS,
    ETC, CARS
}
